bug lá»‡nh search

[2025-07-13 10:38:25,787] ERROR in tree: Ignoring exception in command 'search'
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 852, in _invoke_with_namespace
    transformed_values = await self._transform_arguments(interaction, namespace)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 816, in _transform_arguments
    raise CommandSignatureMismatch(self) from None
discord.app_commands.errors.CommandSignatureMismatch: The signature for command 'search' is different from the one provided by Discord. This can happen because either your code is out of date or you have not synced the commands with Discord, causing the mismatch in data. It is recommended to sync the command tree to fix this issue.ke